### ISSUE TITLE
~/.deno/bin/pup - is not working

### ISSUE THREAD

**Issue by svenskanda** [Hexagon/pup#9] opened 2023-03-18 08:55 UTC
Hej,

the pup i was installed is not working.

![pup_not_working](https://user-images.githubusercontent.com/6360606/226095495-099755d0-0418-4106-92d3-9368507c4ec2.png)

![denon_works](https://user-images.githubusercontent.com/6360606/226095514-c38e156e-a417-411a-8c21-5b185c3a682c.png)

![pup_denon_installdPath](https://user-images.githubusercontent.com/6360606/226095534-fce5366f-58c8-4bc6-835f-99cde7dfaeb4.png)

![pup_install_process](https://user-images.githubusercontent.com/6360606/226095549-b267b0b8-0e95-48cd-b216-1ce249dd3ece.png)

Can you get a solution?

I am the starter of https://github.com/denoland/deno/discussions/18081

**Comment by Hexagon** [comment] 2023-03-18 09:23
Will have a look at that 👍

**Comment by Hexagon** [comment] 2023-03-18 09:33
Thanks for reporting! Problem confirmed on a fresh install, not sure what's going on. Will have a look at it tonight. 👍

**Comment by Pinta365** [comment] 2023-03-18 10:33
@svenskanda there seems to be a documentation problem. It is pointing at the wrong entrypoint. **Install pup.ts**

> deno install -A -n pup https://deno.land/x/pup/pup.ts

**Comment by svenskanda** [comment] 2023-03-18 18:33
Nice - thanks for the solution - it's working.

**Comment by Hexagon** [comment] 2023-03-18 19:33
Documentation is fixed now, both readme and https://hexagon.github.io/pup/installation.html. Thanks!

**Closed by Hexagon** 2023-03-18 19:33 UTC
Labels: documentation

**Comment by svenskanda** [comment] 2023-03-18 21:48
https://github.com/denoland/deno/discussions/18081#discussioncomment-5355676
